= Application Architecture 개요

* 애플리케이션(Application)을 설계하고 구축하는데 사용하는 패턴과 기술
** 애플리케이션 구축시 따라야 할 로드맵과 모범 사례를 제공
** 체계적으로 구성된 애플리케이션을 완성할 수 있도록 함
** 소프트웨어 설계 패턴과 연결되어 보다 일반적인 애플리케이션 아키텍처를 구성

---

애플리케이션 아키텍처는 애플리케이션을 설계하고 구축하는데 사용되는 패턴과 기술입니다. 아키텍처는 애플리케이션을 구축할 때 따라야 할 로드맵과 모범 사례를 제공하여 체계적으로 구성된 애플리케이션을 완성할 수 있게 합니다.

소프트웨어 설계 패턴은 애플리케이션을 구축할 때 도움을 줄 수 있는 정형화된 소프트웨어 설계 방법입니다. 패턴은 문제에 대한 반복가능한 해결책을 알려줍니다.

패턴을 서로 연결해 일반적인 애플리케이션 아키텍처를 만들 수 있습니다. 아키텍처를 직접 완전히 구축하는 대신, 기존 설계 패턴을 사용할 수 있으며 이를 통해 의도한 대로 동작하는 애플리케이션을 만들 수 있습니다.

애플리케이션 아키텍처는 비즈니스에서 사용되는 애플리케이션의 동작을 설명하며 애플리케이션이 애플리케이션간 또는 사용자와 상호작용하는 방식에 중점을 둡니다. 또한 상세한 내부 구조보다는 애플리케이션에서 소비하고 생성하는 데이터에 중점을 둡니다. 애플리케이션 아키텍처에는 비즈니스 기능적 요구사항을 기반으로 지정됩니다. 이는 통합의 문제나 기능 적용 범위의 격차를 식별하는데 도움이 되며, 소프트웨어 수명 주기가 종료되었거나 기술적 오류로 인해 비즈니스에 지장을 줄 수 있는 고유한 기술적 위험이 있는 시스템에 대해 마이그레이션 계획을 세울 수 있도록 합니다.

== 패턴

애플리케이션은 따르는 애플리케이션 아키텍처에 따라 다양한 타입으로 구분될 수 있습니다. 패턴은 아래와 같이 정의할 수 있습니다.

> 실제 상황에서 유용하게 사용되었고 다른 상황에서도 유용할 수 있는 아이디어

애플리케이션은 일반적으로 동일한 패턴을 따르는 다양한 기능의 모음입니다. 이 패턴은 애플리케이션의 패턴을 정의합니다.

애플리케이션 패턴은 구조적(배포/배포 관련) 또는 동작적(프로세스 흐름 또는 상호 작용/통합 관련) 특성을 설명할 수 있으며 애플리케이션 아키텍처는 여러 패턴을 혼합하여 정의될 수 있스빈다. 이런 패턴은 계속 존재해왔지만, GoF(Gang of Four)에 의해 가장 유명하게 대중화되었습니다. 패턴의 대부분은 "애플리케이션 아키텍처" 패턴이 아닌 "소프트웨어 아키텍처" 패턴입니다. Microsoft나 Amazon 같은 대부분의 대규모 소프트웨어 공급업체는 광범위한 패턴 라이브러리를 정리했습니다.

공개된 수많은 패턴에도 불구하고 "업계 표준"으로 간주할 수 있는 패턴은 많지 않습니다. 이들 중 가장 잘 알려진 것 중 일부는 다음과 같습니다.

* **단일 계층/thick 클라이언트/데스크톱 애플리케이션(구조적 패턴)** +
단일 컴퓨터(일반적으로 데스크톱)에만 존재하는 애플리케이션입니다. 물론 여러 컴퓨터에서 동일한 데스크톱 응용 프로그램을 사용할 수 있지만 서로 상호 작용하지는 않습니다(드문 예외 있음).
* **클라이언트-서버/2티어(구조적 패턴)** +
비즈니스 로직, 워크플로우, 통합을 제공하는 백엔드(서버)와 통신하는 리치 클라이언트로 실행되는 프런트엔드(사용자 대면) 레이어로 구성된 애플리케이션 및 데이터 서비스. 단일 사용자인 데스크톱 응용 프로그램과 달리 클라이언트-서버 응용 프로그램은 거의 항상 다중 사용자 응용 프로그램입니다.
* **n 계층(구조적 패턴)** +
서버 기능이 여러 계층으로 분할되어 근거리 통신망(LAN)을 통해 여러 컴퓨터에 분산되는 클라이언트-서버 패턴의 확장입니다.
* **분산(구조적 패턴)** 서버 기능이 WAN(광역 네트워크) 또는 클라우드에 분산되는 n 계층 패턴의 확장입니다. WAN 및 클라우드 배포 시나리오에서 발생할 수 있는 잠재적으로 상당한 대기 시간을 처리하기 위해 서버 기능이 다른 기능과의 비동기 대화에서 더 자율적이고 작동하도록 설계되어야 하기 때문에 이 패턴에는 일부 동작 패턴 속성도 포함됩니다.
* **수평 확장성(구조적 패턴)** 증가하는 처리 부하가 더 큰 서버에 기능을 다시 배포하는 대신 점점 더 많은 수의 기능 인스턴스에 분산될 수 있는 방식으로 여러 컴퓨터에서 서버 기능의 여러 복사본을 실행하는 패턴입니다. 더 강력한 컴퓨터. 클라우드 네이티브 애플리케이션은 기본적으로 수평 확장성을 기반으로 합니다.
이벤트 기반 아키텍처(동작 패턴): 데이터 이벤트(처음에는 장치, 애플리케이션, 사용자, 데이터 저장소 또는 시계에서 시작되었을 수 있음) 및 이벤트를 조건부로 삭제하고, 이벤트 관련 프로세스를 시작하고, 경고를 보낼 수 있는 이벤트 감지 논리 사용자 또는 장치 관리자이거나 데이터 저장소를 업데이트합니다. 이벤트 기반 패턴은 분산 아키텍처 패턴에 필요한 비동기 처리의 기본입니다.
* **ETL(동작 패턴)** 원본 소스에서 데이터를 추출하고 일부 비즈니스 규칙에 따라 해당 데이터를 변환한 다음 해당 데이터를 대상으로 로드하는 애플리케이션 프로세스 패턴입니다. ETL 패턴의 변형에는 ELT와 ETLT가 포함됩니다.
* **요청-응답(행동 패턴)** 애플리케이션이 다른 애플리케이션에 데이터를 요청하고 요청된 데이터가 포함된 응답을 기다리는 데이터 교환을 위한 애플리케이션 통합 패턴입니다. 이는 이전 패턴 설명에서 언급된 비동기 처리와 달리 동기 패턴의 가장 두드러진 예입니다.

올바른 애플리케이션 패턴은 조직의 산업 및 구성 요소 애플리케이션의 사용에 따라 다릅니다. 조직이 유기적으로 성장하고 인수를 통해 성장한 경우 조직은 여러 패턴이 혼합되어 있을 수 있습니다.

애플리케이션 아키텍처에는 Frontend와 Backend 서비스가 모두 있습니다. Frontend 개발이 애플리케이션에서 제공하는 사용자 경험(User experience)에 초점을 맞춘다면, Backend 개발은 데이터 및 서비스, 애플리케이션을 작동하게 하는 기타 기존 시스템에 대한 액세스를 제공하는데 초점을 맞춥니다.

https://www.redhat.com/ko/topics/cloud-native-apps/what-is-an-application-architecture

link:./01_application_architecture.adoc[이전: Module 01 Application Architecture] +
link:./03_client_server.adoc[다음: 클라이언트-서버 아키텍처]