= 애플리케이션 수평 확장

* 애플리케이션은 두 가지 방법으로 확장될 수 있음
* 수직적 크기 조정(Vertical Scaling) - **Scale up**
** CPU, Memory등 리소스의 용량을 변경하는 것을 의미
** 크기를 조정하는 동안 시스템을 사용할 수 없음
* 수평적 크기 조정(Horizontal Scaling) - **Scale out** 또는 **Scale in**
** 리소스 인스턴스(예: 서버)를 추가 또는 제거하는 것을 의미
** 새 리소스가 준비되는 동안에도 서비스는 중단되지 않음
* 수평 확장은 주로 컴퓨팅 리소스에 적용됨
* 데이터베이스 또는 메시지 큐 또한 수평적 조정이 가능하지만, 자동화 되지 않은 데이터 분할이 수반되어야 함

---

IT 인프라에 있어서 네트워크 대역폭, 스토리지, 애플리케이션의 증가율은 예측하기 어렵습니다. 단순히 사용자 증가 뿐만 아니라, 데이터의 증가와 비즈니스의 다양화 등으로 인프라를 확장하거나 축소해야하는 요구사항이 빈번히 발생합니다.

== 수직 확장 (Scale-up)

단순히 말해, 기존의 하드웨어를 높은 사양으로 업그레이드하는 것을 말합니다. 성능이나 용량 증가를 목적으로 하나의 서버에 디스크를 추가하거나 CPU나 메모리를 업그레이드하는 작업을 수직 확장 또는 Scale-up이라고 합니다. 이 작업은 재배포 되는 동안 해당 시스템을 일시적으로 사용할 수 없게 합니다. 따라서, Scale-up은 일반적으로 자동화하지 않습니다.

== 수평 확장(Scale-out)

장비를 추가하여 확장하는 방식을 말합니다. 기존의 서버만으로 용량이나 성능의 한계가 있으면, 비슷한 사양의 서버를 추가하여 연결된 서버에 워크로드를 분담하여 성능을 높이는 방법입니다. 이 경우, 새로운 리소스(예: 웹 서버)를 추가하면 되므로 새 리소스가 준비되는 동안 서비스를 계속할 수 있습니다. 새 리소스 준비가 완료되면 솔루션은 추가 리소스에 배포되며, 수요가 감소하면 리소스를 거둬들일 수 있습니다. 이 작업은 워크로드에 기준하여 자동화 할 수 있습니다.

== 자동 크기 조정(Autoscaling)

자동 크기 조정은 성능 요구사항에 맞게 리소스를 동적으로 할당하는 프로세스입니다. 워크로드가 증가하면 애플리케이션은 원하는 성능 수준을 유지(SLA 약정 준수)하기 위해 추가 리소스가 필요합니다. 수요가 감소하여 추가 리소스가 필요 없어지면 할당을 취소할 수 있습니다.

자동 크기 조정은 관리 부담을 줄이면서 탄력적으로 리소스를 운영할 수 있도록 해 줍니다. 운영자가 시스템 리소스를 지속적으로 모니터링하고 리소스 추가 또는 제거를 결정할 필요가 줄어듭니다.

link:./05_n-tier_architecture.adoc[이전: N-Tier 아키텍처] +
link:./07_microservice.adoc[다음: 마이크로서비스 아키텍처]