= JSP 기본 태그

[%header, cols="1, 3, 1"]
|===
|종류|용도|형식
|지시어(Directrive)|JSP 페이지의 속성을 지정|`<%@ %>`
|주석(Comment)|JSP 페이지의 설명 삽입|`<%-- -\->`
|선언부(Declaration)|변수와 메소드를 선언|`<%! %>`
|표현식(Expression)|계산식이나 함수를 호출한 결과를 문자열 형태로 출력|`<%= %>`
|스크립틀릿(Scriptlet)|Java 코드를 기술|`<% %>`
|액션 태그|Java Bean이나 Applet Server Module과 연결|`<jsp:action> </jsp:action>`
|===

---

JSP는 HTML내에 Java 코드를 삽입하여 웹 서버에서 동적으로 웹 페이지를 생성하도록 합니다. 웹 페이지 내에서 HTML 코드와 Java 코드를 분리하기 위해 tag를 사용할 수 있습니다.

== 지시어(Directive)

지시어는 JSP 페이지를 Java 코드로 변환하는데 필요한 정보를 JSP 엔진에 알려주며, 주로 스크립트 언어나 인코딩 방식 등을 지정합니다. 기본 구문은 다음과 같습니다.

* **page** JSP 페이지의 전체적인 속성 지정
* **include** 다른 페이지를 현재 페이지에 삽입
* **taglib** 태그 라이브러리의 태그를 사용

=== page 지시어

page 지시어는 문서 타입, 에러 페이지, MIME 타입등의 JSP 페이지에 대한 정보를 설정합니다.

[%header, cols="1, 3, 1"]
|===
|속성|내용|기본값
|info|페이지에 대한 설명을 입략합니다|없음
|language|페이지에 사용할 스크립트 언어를 지정|Java
|contentType|페이지에서 생성할 MIME 타입을 지정|없음
|pageEncoding|charset과 같이 인코딩을 지정함|ISO-8859-1
|import|페이지에서 사용할 Java 패키지와 클래스를 지정|없음
|session|세션 사용 여부를 지정|없음
|buffer|출력 버퍼의 크기를 지정, 사용하지 않으려면 none으로 지정|8KB
|autoFlush|출력 버퍼가 모두 채워졌을 때 자동으로 비울지 지정|true
|trimDirectiveWhitespaces|지시어언선으로 생긴 공백을 제거할지 여부 지정|true
|errorPage|해당 페이지에서 오류가 발생했을 때 오류 여부를 보여줄 페이지를 지정|없음
|isErrorPage|해당 페이지가 오류 페이지인지 여부|false
|===

아래 지시어는 해당 JSP 페이지의 스크립트 언어를 Java로, contentType을 text/html, UTF-8로, pageEncoding을 UTF-8로 지정합니다.

----
<%@ page language="java" contentType="text/html; charset-UTF-8" pageEncoding="UTF-8" %>
----

아래 지시어는 해당 JSP 페이지에서 java.util.List와 java.util.ArrayList 클래스를 import 합니다.

----
<%@ import java.util.List %>
<%@ import java.util.ArrayList %>
----

=== include 지시어

다른 JSP 페이지를 현재 페이지에 삽입합니다.  형식은 아래와 같습니다.

----
<@ include file="file_name.jsp" %>
----

include 지시어로 JSP 문서를 다른 페이지에 포함시키면 먼저 파일의 내용 그대로를 페이지에 삽입한 후 컴파일됩니다. 

=== taglib 지시어

Expressional Language에서 Java 클래스의 메소드를 호출하거나 Java Standard Tag Library(JSTL)을 사용하도록 지정합니다.

== 선언부(Declaration)

페이지내에서 변수와 메소드를 선언하기 위한 태그로, `<%! ... %>` 태그를 사용합니다. 여기에서 선언한 변수와 메소드는 Servlet 코드로 변환되었을 때 클래스의 필드와 메소드로 동작하며, 선언된 변수와 메소드는 JSP 페이지 전체에 적용됩니다. `<% ... %>` 와 비슷하지만 선언 태그에서는 메소드를 선언하고 작성할 수 있습니다.


== 표현식(Expression)

계산식이나 함수를 호출한 결과를 문자열 형태로 출력하며, 형식은 아래와 같습니다.

----
<%= String_expression %>
----

== 스크립틀릿(Scriptlet)

JSP 페이지가 요청을 받을 때 실행되어야 할 Java 코드를 작성합니다. Servlet 코드로 변환되면 _jspService() 메소드로 옮겨집니다. 형식은 아래와 같습니다.

----
<%
    Java Code
%>
----

Java 언어에서는 메소드 내부에서 메소드를 선언할 수 없는데, 따라서 스크립틀릿 내부에서는 메소드를 선언할 수 없습니다. JSP에서 클래스 변수와 메소드는 선언부에서 정의해야 하며, 스크립틀릿에서는 선언한 변수와 메소드를 사용만 할 수 있습니다.

link:./05_jsp_file.adoc[이전: JSP 파일 형식] +
link:./07_lab3-1.adoc[다음: Lab 3-1 간단한 JSP 응용 프로그램 생성]