= Lab 3-3 session 객체를 이용한 로그인 처리

이 연습에서는 연습 3-2에서 작성한 프로그램에 링크 기능과 상품 검색 기능을 추가합니다. 아래 절차에 따릅니다.

== 연습 1 실습 파일 준비

=== Windows 11에서 실습 파일 준비

1. 아래 링크에서 실습 파일을 다운로드 합니다.
+
https://github.com/gikpreet/class-servlet-jsp/blob/main/Module%2003%20JSP/LabFile/lab3-3.zip
+
2. 다운로드한 파일의 압축을 해제합니다.
3. 압축을 해제한 폴더의 Starter 폴더를 c:\apache-tomcat-9.8.xx\webapps 폴더로 복사합니다.
4. 웹 브라우저를 실행하여 http://localhost:8080 으로 이동하고, Manager App 버튼을 클릭합니다.
5. 로그인 창에서, 사용자 이름과 비밀번호에 admin을 입력하고 로그인합니다.
6. Tomcat 웹 애플리케이션에서 /lab3-2 애플리케이션을 확인합니다.
7. /lab3-2 애플리케이션을 클릭하여 엽니다. 아래와 같은 웹 애플리케이션이 실행됩니다.
8. c:\apache-tomcat-9.8.xx\webapps\lab3-3 폴더를 Visual Studio Code에서 엽니다.

== macOS에서 실습 파일 준비

1. 아래 링크에서 실습 파일을 다운로드 합니다.
+
https://github.com/gikpreet/class-servlet-jsp/blob/main/Module%2003%20JSP/LabFile/lab3-3.zip
+
2. 다운로드한 파일의 압축을 해제합니다.
3. 압축을 해제한 폴더의 Starter 폴더를 /opt/homebrew/Cellar/tomcat@9/9.0.85/libexec/webapps 디렉토리로 복사합니다.
4. 웹 브라우저를 실행하여 http://localhost:8080 으로 이동하고, Manager App 버튼을 클릭합니다.
5. 로그인 창에서, 사용자 이름과 비밀번호에 admin을 입력하고 로그인합니다.
6. Tomcat 웹 애플리케이션에서 /lab3-1 애플리케이션을 확인합니다.
7. /lab3-2 애플리케이션을 클릭하여 엽니다. 아래와 같은 웹 애플리케이션이 실행됩니다.
8. /opt/homebrew/Cellar/tomcat@9/9.0.85/libexec/webapps/lab3-3 폴더를 Visual Studio Code에서 엽니다.

== Linux(Ubuntu)에서 실습 파일 준비

1. 아래 링크에서 실습 파일을 다운로드 합니다.
+
https://github.com/gikpreet/class-servlet-jsp/blob/main/Module%2003%20JSP/LabFile/lab3-3.zip
+
2. 다운로드한 파일의 압축을 해제합니다.
3. 압축을 해제한 폴더의 Starter 폴더를 /var/lib/tomcat9/webapps 디렉토리로 복사합니다.
+
----
$ cp -r ~/Downloads/lab3-2/ /var/lib/tomcat9/webapps/
----
4. 웹 브라우저를 실행하여 http://localhost:8080 으로 이동하고, Manager App 버튼을 클릭합니다.
5. 로그인 창에서, 사용자 이름과 비밀번호에 admin을 입력하고 로그인합니다.
6. Tomcat 웹 애플리케이션에서 /lab3-1 애플리케이션을 확인합니다.
7. /lab3-1 애플리케이션을 클릭하여 엽니다. 아래와 같은 웹 애플리케이션이 실행됩니다.
8. /var/lib/tomcat9/webapps/lab3-1 폴더를 Visual Studio Code에서 엽니다.

== 연습 2 로그인 처리

1. login.jsp 페이지를 열고 코드를 확인합니다. JSP 페이지에는 <form> 태그가 포함되어 있으며, POST 메소드로 loginprocess.jsp 페이지에 요청을 전송합니다.
+
[source, html]
----
<%@ page language="java" contentType="text/html" pageEncoding="UTF-8" %>

<%@ page import="java.util.List" %>
<%@ page import="java.util.ArrayList" %>
<%@ page import="book.BookInList" %>
<%@ page import="book.BookFactory" %>

<%@ include file="./header.jsp" %>

<table width="1000">
    <tr>
        <td>
            <table width=600>
                <tr>
                <form method="post" action="loginprocess.jsp">
                    <td height="10">
                        <input type="text" name="userID" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="password" name="password" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="로그인" />        
                    </td>
                </tr>
                </form>
            </tr>
            </table>
        </td>
    </tr>
</table>

<%@ include file="./tail.jsp" %>
----
+
2. loginprocess.jsp 페이지를 열고 Toto 1 구역에 로그인 코드를 아래 요구대로 작성합니다.
a. 요청 인코딩을 UTF-8로 지정합니다.
b. 요청 파라미터 userID와 password를 문자열 변수로 저장합니다.
c. UserFactory 싱글턴 객체의 login 메소드를 파라미터로 userID와 password를 호출합니다.
d. login 메소드의 실행 결과가 true이면  
A. UserFactory 싱글턴 객체의 getUser 메소드를 userID를 파라미터로 전달하여 User 객체를 반환받습니다.
B. userName 세션 속성에 User 객체의 이름(getUserName 메소드)를 할당합니다.
C. index.jsp 페이지로 리다이렉트합니다.
e. login 메소드의 실행 결과가 false이면 JavaScript 오류 메시지를 보여주고 login.jsp 페이지로 리다이렉트합니다.
3. 코드는 아래와 유사할 것입니다.
+
[source, java]
----
<%@ page language="java" contentType="text/html" pageEncoding="UTF-8" %>

<%@ page import="book.User" %>
<%@ page import="book.UserFactory" %>

<%
    request.setCharacterEncoding("UTF-8");
    String userID = request.getParameter("userID");
    String password = request.getParameter("password");
    User result = null;

    if (UserFactory.getUserFactory().login(userID, password)) {
        result = UserFactory.getUserFactory().getUser(userID);
        session.setAttribute("userName", result.getUserName());
        response.sendRedirect("index.jsp");
    }
    else {
        out.print("<script>alert('login fail');history.back();</script>");
        response.sendRedirect("login.jsp");
    }
%>
----
+
4. header.jsp 페이지를 열고 Todo 2 구역에 userName 세션 변수를 보여주는 코드를 작성합니다.
a. userName 세션 변수가 null이면 userName 변수에 세션 ID를 할방합니다.
b. userName 세션 변수가 유효하면 userName 세션 변수를 userName 변수에 할당합니다.
5. 코드는 아래와 유사할 것입니다.
+
[source, java]
----
String userName = "";
if (session.getAttribute("userName") == null) {
    userName = session.getId();
}
else {
    userName = session.getAttribute("userName").toString();
}
----
+
6. 로그인 페이지(login.jsp)로 이동합니다.
7. Julie, P@ssw0rd를 사용하여 로그인합니다.
8. index.jsp 페이지의 오른쪽 상단에서 사용자의 이름을 확인합니다.