= exception 객체

* JSP 응용 프로그램이 동작 중 발생한 예외 저장
* JSP 페이지에서 예외가 발생하였을 경우, 예외를 처리할 페이지에 전달
* Page 지시자에서 isErrorPage 속성이 true로 지정된 페이지에서 예외를 표시하고 처리

---

java.lang.Exception 타입인 exception 내장 객체는 JSP 페이지에서 예외가 발생하였을 경우, 예외를 처리할 페이지에 전달되는 객체입니다. page 지시어의 isErrorPage 속성을 true로 지정한 JSP 페이지에서만 사용 가능한 내장 객체로 사용은 Java의 Exception 타입 객체와 동일합니다.

@page 지시어에서 아래와 같이 isErrorPage 속성이 true로 지정되었다면,

----
<%@ page isErrorPage="true" %>
----

페이지에서 발생한 Exception을 처리할 수 있습니다.

[source, java]
----
<%
    String errorName = exception.getClass().getName();
    String message = exception.getMessage();
%>
----

JSP에서는 JSP 페이지에 errorPage를 지정해 주거나, web.xml 파일에서 오류 페이지를 정의하고 발생한 Exception을 처리하도록 할 수 있습니다.

page 디렉티브에서 아래와 같이 errorPage에 오류발생시 처리할 페이지를 선언하면 현재 페이지에서 오류가 발생할 경우 지정한 페이지로 이동하고, 이동한 페이지에서 exception 내장 객체를 사용하여 오류를 처리할 수 있습니다.

----
<%@ page errorPage="error.jsp"%>
----

다른 방법으로, web.xml 파일에서 아래와 같이 exception 타입, HTML 오류 코드, 오류 처리 페이지의 위치를 입력하면 해당 페이지에서 오류가 발생할 경우 지정한 오루 처리 페이지로 자동으로 이동하고, 오류를 처리할 수 있습니다.

[source, xml]
----
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" version="3.0" metadata-complete="true">

    <error-page>
        <exception-type>java.lang.NumberFormatException</exception-type>
        <location>/NumberFormatError.jsp</location>
    </error-page>

    <error-page>
        <error-code>404</error-code>
        <location>/NotFoundError.jsp</location>
    </error-page>
</web-app>
----

link:./20_page.adoc[이전: page 객체] +
link:./22_lab3-4.adoc[다음: Lab 3-4 오류 페이지 처리]